// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV8nMk5-BshMF1OqIiQFOsccDXDLnufSY',
    appId: '1:424910647692:web:f3c3fdb92e87bea08626a9',
    messagingSenderId: '424910647692',
    projectId: 'biblio-fac',
    authDomain: 'biblio-fac.firebaseapp.com',
    storageBucket: 'biblio-fac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6vvQJxSniZkxta9rRREuHj1qkyu_d2UI',
    appId: '1:424910647692:android:d2dca5a9898c9df98626a9',
    messagingSenderId: '424910647692',
    projectId: 'biblio-fac',
    storageBucket: 'biblio-fac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFDd1p_uR0IhRHnyBUacCO4dP8bTjWIJk',
    appId: '1:424910647692:ios:cd5666ac132f61e58626a9',
    messagingSenderId: '424910647692',
    projectId: 'biblio-fac',
    storageBucket: 'biblio-fac.firebasestorage.app',
    iosBundleId: 'com.example.biblioFac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFDd1p_uR0IhRHnyBUacCO4dP8bTjWIJk',
    appId: '1:424910647692:ios:cd5666ac132f61e58626a9',
    messagingSenderId: '424910647692',
    projectId: 'biblio-fac',
    storageBucket: 'biblio-fac.firebasestorage.app',
    iosBundleId: 'com.example.biblioFac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV8nMk5-BshMF1OqIiQFOsccDXDLnufSY',
    appId: '1:424910647692:web:9c0ae73fbd8ccc788626a9',
    messagingSenderId: '424910647692',
    projectId: 'biblio-fac',
    authDomain: 'biblio-fac.firebaseapp.com',
    storageBucket: 'biblio-fac.firebasestorage.app',
  );
}
